# Generated by scripts/prepare_windows_outbound_bootstrap.py
# Run from a Windows checkout of factory-v3 after ao-worker.exe is installed.
$ErrorActionPreference = "Stop"

$FactoryRoot = if ($env:FACTORY_V3_ROOT) { $env:FACTORY_V3_ROOT } else { "C:\workspace\factory-v3" }
$AoWorker = if ($env:AO_WORKER_EXE) { $env:AO_WORKER_EXE } else { "$env:USERPROFILE\.cargo\bin\ao-worker.exe" }
$UbuntuTarget = if ($env:FACTORY_V3_UBUNTU_TARGET) { $env:FACTORY_V3_UBUNTU_TARGET } else { "ubuntu-user@ubuntu-host" }

if (-not (Test-Path $FactoryRoot)) { throw "factory-v3 checkout not found: $FactoryRoot" }
if (-not (Test-Path $AoWorker)) { throw "ao-worker.exe not found: $AoWorker" }
if (-not $env:AO_WORKER_ENROLLMENT_TOKEN) { $env:AO_WORKER_ENROLLMENT_TOKEN = "<set AO_WORKER_ENROLLMENT_TOKEN>" }
if ($env:AO_WORKER_ENROLLMENT_TOKEN -like "<*") { throw "Set AO_WORKER_ENROLLMENT_TOKEN before starting the worker" }

$ProviderPathEntries = @(
    (Join-Path $env:APPDATA "npm"),
    (Join-Path $env:USERPROFILE ".cargo\bin")
) | Where-Object { Test-Path $_ }
$env:PATH = (($ProviderPathEntries + @($env:PATH)) -join [IO.Path]::PathSeparator)

$CodexExe = Join-Path $env:USERPROFILE ".cargo\bin\codex.exe"
$CodexCmd = Join-Path $env:APPDATA "npm\codex.cmd"
if (-not (Test-Path $CodexExe)) {
    if (-not (Test-Path $CodexCmd)) {
        throw "codex.cmd not found: $CodexCmd"
    }
    $Rustc = Get-Command rustc.exe -ErrorAction SilentlyContinue
    if (-not $Rustc) {
        $RustcPath = Join-Path $env:USERPROFILE ".cargo\bin\rustc.exe"
        if (Test-Path $RustcPath) {
            $Rustc = Get-Item $RustcPath
        }
    }
    if (-not $Rustc) {
        throw "codex.exe shim is missing and rustc.exe is unavailable to build it"
    }
    $ShimSource = Join-Path $env:TEMP "factory-v3-codex-forwarder.rs"
    @'
use std::env;
use std::path::PathBuf;
use std::process::{Command, Stdio};

fn main() {
    let appdata = match env::var("APPDATA") {
        Ok(v) => v,
        Err(_) => {
            eprintln!("APPDATA is not set; cannot locate npm codex.cmd");
            std::process::exit(127);
        }
    };
    let target: PathBuf = [appdata.as_str(), "npm", "codex.cmd"].iter().collect();
    if !target.is_file() {
        eprintln!("codex.cmd not found at {}", target.display());
        std::process::exit(127);
    }
    let mut cmd = Command::new("cmd.exe");
    cmd.arg("/C").arg(target);
    for arg in env::args_os().skip(1) {
        cmd.arg(arg);
    }
    let status = cmd.stdin(Stdio::inherit()).stdout(Stdio::inherit()).stderr(Stdio::inherit()).status();
    match status {
        Ok(s) => std::process::exit(s.code().unwrap_or(1)),
        Err(e) => {
            eprintln!("failed to launch codex.cmd: {e}");
            std::process::exit(127);
        }
    }
}
'@ | Set-Content -Path $ShimSource -Encoding ASCII
    & $Rustc.Source $ShimSource -O -o $CodexExe
}
& $CodexExe --version | Out-Null

$env:AO_COORDINATOR_URL = "http://127.0.0.1:50051"
$env:AO_WORKER_NODE_ID = "windows-live-worker"
$env:AO_WORKER_LABEL = "Windows AO worker"
$env:AO_WORKER_ADAPTERS = "codex,claude,fake"
$env:AO_WORKER_TAGS = "win"
$env:AO_WORKER_RUNTIME_BIND = "127.0.0.1:60053"
$env:AO_WORKER_RUNTIME_PUBLIC_URL = "http://127.0.0.1:60053"
$env:FACTORY_V3_WORKER_RUNTIME_REMOTE_PORT = "60053"
$env:FACTORY_V3_WORKER_RUNTIME_LOCAL_PORT = "60053"

$Tunnel = Start-Process -FilePath "powershell" -ArgumentList @(
    "-NoProfile",
    "-ExecutionPolicy", "Bypass",
    "-File", (Join-Path $FactoryRoot "scripts\cross-host-tunnel.ps1"),
    $UbuntuTarget,
    "50051",
    "50051",
    "60053",
    "60053"
) -PassThru

Start-Sleep -Seconds 3
$Worker = Start-Process -FilePath $AoWorker -PassThru

[ordered]@{
    schema = "factory-v3/windows-outbound-bootstrap/v1/windows-return"
    verdict = "STARTED"
    node_id = $env:AO_WORKER_NODE_ID
    tags = $env:AO_WORKER_TAGS
    coordinator_url = $env:AO_COORDINATOR_URL
    runtime_public_url = $env:AO_WORKER_RUNTIME_PUBLIC_URL
    tunnel_pid = $Tunnel.Id
    worker_pid = $Worker.Id
} | ConvertTo-Json -Depth 4
