#!/usr/bin/env python3
"""Prepare a Windows-initiated v0.2 worker bootstrap bundle.

Windows hosts managed by MDM may allow outbound SSH to Ubuntu while rejecting
inbound SSH from Ubuntu. This script writes operator-safe bootstrap artifacts
for that topology. It deliberately does not commit enrollment tokens; any
secret token stays in a local, ignored handoff file.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_DIR = ROOT / "run-artifacts/release-v0.2/windows-outbound-bootstrap"
SCHEMA = "ao-operator/windows-outbound-bootstrap/v1"


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def bootstrap_ps1(
    *,
    ubuntu_target: str,
    node_id: str,
    tags: str,
    runtime_port: int,
    token_placeholder: str,
) -> str:
    return f"""# Generated by scripts/prepare_windows_outbound_bootstrap.py
# Run from a Windows checkout of ao-operator after ao-worker.exe is installed.
$ErrorActionPreference = "Stop"

$FactoryRoot = if ($env:FACTORY_V3_ROOT) {{ $env:FACTORY_V3_ROOT }} else {{ "C:\\workspace\\ao-operator" }}
$AoWorker = if ($env:AO_WORKER_EXE) {{ $env:AO_WORKER_EXE }} else {{ "$env:USERPROFILE\\.cargo\\bin\\ao-worker.exe" }}
$UbuntuTarget = if ($env:FACTORY_V3_UBUNTU_TARGET) {{ $env:FACTORY_V3_UBUNTU_TARGET }} else {{ "{ubuntu_target}" }}

if (-not (Test-Path $FactoryRoot)) {{ throw "ao-operator checkout not found: $FactoryRoot" }}
if (-not (Test-Path $AoWorker)) {{ throw "ao-worker.exe not found: $AoWorker" }}
if (-not $env:AO_WORKER_ENROLLMENT_TOKEN) {{ $env:AO_WORKER_ENROLLMENT_TOKEN = "{token_placeholder}" }}
if ($env:AO_WORKER_ENROLLMENT_TOKEN -like "<*") {{ throw "Set AO_WORKER_ENROLLMENT_TOKEN before starting the worker" }}

$ProviderPathEntries = @(
    (Join-Path $env:APPDATA "npm"),
    (Join-Path $env:USERPROFILE ".cargo\\bin")
) | Where-Object {{ Test-Path $_ }}
$env:PATH = (($ProviderPathEntries + @($env:PATH)) -join [IO.Path]::PathSeparator)

$CodexExe = Join-Path $env:USERPROFILE ".cargo\\bin\\codex.exe"
$CodexCmd = Join-Path $env:APPDATA "npm\\codex.cmd"
if (-not (Test-Path $CodexExe)) {{
    if (-not (Test-Path $CodexCmd)) {{
        throw "codex.cmd not found: $CodexCmd"
    }}
    $Rustc = Get-Command rustc.exe -ErrorAction SilentlyContinue
    if (-not $Rustc) {{
        $RustcPath = Join-Path $env:USERPROFILE ".cargo\\bin\\rustc.exe"
        if (Test-Path $RustcPath) {{
            $Rustc = Get-Item $RustcPath
        }}
    }}
    if (-not $Rustc) {{
        throw "codex.exe shim is missing and rustc.exe is unavailable to build it"
    }}
    $ShimSource = Join-Path $env:TEMP "ao-operator-codex-forwarder.rs"
    @'
use std::env;
use std::path::PathBuf;
use std::process::{{Command, Stdio}};

fn main() {{
    let appdata = match env::var("APPDATA") {{
        Ok(v) => v,
        Err(_) => {{
            eprintln!("APPDATA is not set; cannot locate npm codex.cmd");
            std::process::exit(127);
        }}
    }};
    let target: PathBuf = [appdata.as_str(), "npm", "codex.cmd"].iter().collect();
    if !target.is_file() {{
        eprintln!("codex.cmd not found at {{}}", target.display());
        std::process::exit(127);
    }}
    let mut cmd = Command::new("cmd.exe");
    cmd.arg("/C").arg(target);
    for arg in env::args_os().skip(1) {{
        cmd.arg(arg);
    }}
    let status = cmd.stdin(Stdio::inherit()).stdout(Stdio::inherit()).stderr(Stdio::inherit()).status();
    match status {{
        Ok(s) => std::process::exit(s.code().unwrap_or(1)),
        Err(e) => {{
            eprintln!("failed to launch codex.cmd: {{e}}");
            std::process::exit(127);
        }}
    }}
}}
'@ | Set-Content -Path $ShimSource -Encoding ASCII
    & $Rustc.Source $ShimSource -O -o $CodexExe
}}
& $CodexExe --version | Out-Null

$env:AO_COORDINATOR_URL = "http://127.0.0.1:50051"
$env:AO_WORKER_NODE_ID = "{node_id}"
$env:AO_WORKER_LABEL = "Windows AO worker"
$env:AO_WORKER_ADAPTERS = "codex,claude,fake"
$env:AO_WORKER_TAGS = "{tags}"
$env:AO_WORKER_RUNTIME_BIND = "127.0.0.1:{runtime_port}"
$env:AO_WORKER_RUNTIME_PUBLIC_URL = "http://127.0.0.1:{runtime_port}"
$env:FACTORY_V3_WORKER_RUNTIME_REMOTE_PORT = "{runtime_port}"
$env:FACTORY_V3_WORKER_RUNTIME_LOCAL_PORT = "{runtime_port}"

$Tunnel = Start-Process -FilePath "powershell" -ArgumentList @(
    "-NoProfile",
    "-ExecutionPolicy", "Bypass",
    "-File", (Join-Path $FactoryRoot "scripts\\cross-host-tunnel.ps1"),
    $UbuntuTarget,
    "50051",
    "50051",
    "{runtime_port}",
    "{runtime_port}"
) -PassThru

Start-Sleep -Seconds 3
$Worker = Start-Process -FilePath $AoWorker -PassThru

[ordered]@{{
    schema = "{SCHEMA}/windows-return"
    verdict = "STARTED"
    node_id = $env:AO_WORKER_NODE_ID
    tags = $env:AO_WORKER_TAGS
    coordinator_url = $env:AO_COORDINATOR_URL
    runtime_public_url = $env:AO_WORKER_RUNTIME_PUBLIC_URL
    tunnel_pid = $Tunnel.Id
    worker_pid = $Worker.Id
}} | ConvertTo-Json -Depth 4
"""


def readme_md(*, ubuntu_target: str, node_id: str, tags: str, runtime_port: int) -> str:
    return f"""# Windows Outbound Worker Bootstrap

Status: READY_FOR_WINDOWS_INITIATED_RUN

MDM blocks Ubuntu-initiated SSH into Windows. The supported v0.2 W4 topology is
Windows initiating outbound SSH to Ubuntu, then starting `ao-worker.exe`
locally with tag `{tags}`.

Generated assets:

- `bootstrap-windows-worker.ps1` starts `scripts/cross-host-tunnel.ps1` with
  both the coordinator forward and worker RuntimeService reverse forward.
- `windows-outbound-bootstrap.json` records the non-secret bootstrap plan.

Runtime values:

- Ubuntu target: `{ubuntu_target}`
- Windows node id: `{node_id}`
- Windows tags: `{tags}`
- Coordinator forward: Windows `127.0.0.1:50051` -> Ubuntu `127.0.0.1:50051`
- Worker runtime reverse forward: Ubuntu `127.0.0.1:{runtime_port}` -> Windows
  `127.0.0.1:{runtime_port}`

The generated PowerShell intentionally contains no real enrollment token. Set
`AO_WORKER_ENROLLMENT_TOKEN` on Windows from the local secret handoff before
running it.

The bootstrap prepends the user npm and Cargo bin directories to `PATH` before
starting `ao-worker.exe`. It also ensures `%USERPROFILE%\\.cargo\\bin\\codex.exe`
exists as a real executable forwarder to `%APPDATA%\\npm\\codex.cmd`, because the
Windows worker process cannot rely on npm's `.cmd` shim when it spawns `codex`.
"""


def build_report(
    *,
    ubuntu_target: str,
    node_id: str,
    tags: str,
    runtime_port: int,
    output_dir: Path,
    secret_handoff: Path | None,
) -> dict[str, Any]:
    def display(path: Path) -> str:
        try:
            return str(path.relative_to(ROOT))
        except ValueError:
            return str(path)

    return {
        "schema": SCHEMA,
        "generated_at": utc_now(),
        "dispatch_authorized": False,
        "live_providers_run": False,
        "topology": "windows-initiated-outbound-ssh",
        "ubuntu_target": ubuntu_target,
        "windows_node_id": node_id,
        "windows_tags": tags.split(","),
        "coordinator_forward": {
            "windows_local": "127.0.0.1:50051",
            "ubuntu_remote": "127.0.0.1:50051",
        },
        "worker_runtime_reverse_forward": {
            "ubuntu_remote": f"127.0.0.1:{runtime_port}",
            "windows_local": f"127.0.0.1:{runtime_port}",
        },
        "artifacts": {
            "readme": display(output_dir / "README.md"),
            "bootstrap_script": display(output_dir / "bootstrap-windows-worker.ps1"),
        },
        "secret_handoff": str(secret_handoff) if secret_handoff else "not-written",
        "codex_path_ready": True,
        "blockers": [
            "W4 is not complete until this bootstrap is executed from Windows and the coordinator observes a worker tagged win."
        ],
        "next_safe_command": "Run bootstrap-windows-worker.ps1 from Windows so Windows initiates the tunnel to Ubuntu with provider CLI paths available to ao-worker.",
        "verdict": "READY_FOR_WINDOWS_INITIATED_RUN",
    }


def write_outputs(
    *,
    output_dir: Path,
    ubuntu_target: str,
    node_id: str,
    tags: str,
    runtime_port: int,
    token_placeholder: str,
    secret_handoff: Path | None,
) -> dict[str, Any]:
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "bootstrap-windows-worker.ps1").write_text(
        bootstrap_ps1(
            ubuntu_target=ubuntu_target,
            node_id=node_id,
            tags=tags,
            runtime_port=runtime_port,
            token_placeholder=token_placeholder,
        ),
        encoding="utf-8",
    )
    (output_dir / "README.md").write_text(
        readme_md(ubuntu_target=ubuntu_target, node_id=node_id, tags=tags, runtime_port=runtime_port),
        encoding="utf-8",
    )
    if secret_handoff:
        secret_handoff.parent.mkdir(parents=True, exist_ok=True)
        secret_handoff.write_text(
            "AO_WORKER_ENROLLMENT_TOKEN=<set-windows-node-token-here>\n",
            encoding="utf-8",
        )
        secret_handoff.chmod(0o600)
    report = build_report(
        ubuntu_target=ubuntu_target,
        node_id=node_id,
        tags=tags,
        runtime_port=runtime_port,
        output_dir=output_dir,
        secret_handoff=secret_handoff,
    )
    (output_dir / "windows-outbound-bootstrap.json").write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return report


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Prepare Windows-initiated v0.2 worker bootstrap artifacts.")
    parser.add_argument("--ubuntu-target", default="ubuntu-user@ubuntu-host")
    parser.add_argument("--node-id", default="windows-live-worker")
    parser.add_argument("--tags", default="win")
    parser.add_argument("--runtime-port", type=int, default=60053)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--secret-handoff", type=Path, default=None)
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args(argv)

    report = write_outputs(
        output_dir=args.output_dir,
        ubuntu_target=args.ubuntu_target,
        node_id=args.node_id,
        tags=args.tags,
        runtime_port=args.runtime_port,
        token_placeholder="<set AO_WORKER_ENROLLMENT_TOKEN>",
        secret_handoff=args.secret_handoff,
    )
    if args.json:
        print(json.dumps(report, indent=2, sort_keys=True))
    else:
        print(f"verdict={report['verdict']}")
        print(f"artifact={report['artifacts']['bootstrap_script']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
